
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - dbt_utils.at_least_one

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: hello_world
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: film_test
      columns:
          - name: rating
            tests:
              - accepted_values:
                 values: ['NC-17','PG-13','R','G','PG']

          - name: language_id
            tests:
                - accepted_values:
                   values: [1,2]
                   quote: false

    - name: payment_inc
      columns:
          - name: payment_id
            tests:
                - unique
                - not_null




sources:
  - name: stg_example
    database: sakila_wh
    schema: stg
    tables:
     - name: film
     - name: customer
